eksctl create cluster \
  --version 1.17 \
  --region us-east-1 \
  --name=devopscapstone \
  --ssh-access=true \
  --ssh-public-key=jenkinsdevopsc3 \
  --nodegroup-name=capstone-workers \
  --node-type=t2.small \
  --nodes=3 \
  --nodes-min=1 \
  --nodes-max=4
  --node-ami auto